# Configuration for GitHub Labeler
# Save this as: .github/labeler.yml

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - '*.md'
      - 'docs/**/*'
      - 'README*'

# Frontend changes
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/components/**/*'
      - 'src/pages/**/*'
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
      - '*.css'
      - '*.scss'
      - '*.html'

# Backend changes
backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/api/**/*'
      - 'src/server/**/*'
      - '*.py'
      - '*.java'
      - '*.go'
      - '*.php'

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - '**/*.test.*'
      - '**/*.spec.*'
      - '__tests__/**/*'

# Configuration files
config:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'requirements.txt'
      - 'Dockerfile'
      - '*.yml'
      - '*.yaml'
      - '*.toml'
      - '*.ini'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'requirements.txt'
      - 'Pipfile'
      - 'composer.json'
