# This workflow will triage pull requests and apply labels based on the
# paths that are modified in the pull request.
name: "Pull Request Labeler"

on:
  pull_request_target

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Apply labels
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true
